name: cf-feedstock-ops
channels:
  - conda-forge
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - boltons >=23.0.0
  - click
  - conda
  - conda-build >=3.27
  - conda-forge-metadata >=0.11.0
  - conda-package-handling
  - conda-recipe-manager
  - conda-smithy >=2026
  - jinja2
  - orjson
  - pixi
  - py-rattler >=0.22.0,<0.26a0
  - pydantic >=2.13
  - pydantic-settings >=2.15.0,<3.0.0
  - rattler-build-conda-compat >=1.4.15,<2.0.0a0
  - requests
  - ruamel.yaml
  - ruamel.yaml.jinja2
  - wurlitzer
  - zstandard
  # build
  - python >=3.11
  - pip
  - python-build
  - setuptools
  - setuptools_scm
  # dev dependencies
  - flaky
  - pytest
