name: tests

on:
  push:
    branches:
      - main
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: mamba-org/setup-micromamba@0dea6379afdaffa5d528b3d1dabc45da37f443fc # v1
        with:
          environment-file: environment.yml
          micromamba-version: "1.5.10-0"

      - name: configure conda and install code
        run: |
          pip install --no-deps --no-build-isolation -e .

      - name: test versions
        run: |
          cd ..
          python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ != '0.0.0'"
          cd -

          pip uninstall conda-forge-feedstock-ops --yes
          rm -rf dist/*
          python -m build --sdist . --outdir dist
          pip install --no-deps --no-build-isolation dist/*.tar.gz
          cd ..
          python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ != '0.0.0'"
          cd -
          pip uninstall conda-forge-feedstock-ops --yes

          python -m pip install -v --no-deps --no-build-isolation -e .

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        with:
          context: .
          push: false
          load: true
          tags: conda-forge-feedstock-ops:test

      - name: ensure cli runs
        run: |
          conda-forge-feedstock-ops-container --help

      - name: run tests
        run: |
          pytest -vvs tests
