name: tests

on:
  push:
    branches:
      - main
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v1
        with:
          environment-file: environment.yml
          micromamba-version: "1.5.10-0"

      - name: configure conda and install code
        run: |
          pip install --no-deps --no-build-isolation -e .

      - name: test versions
        run: |
          cd ..
          python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ != '0.0.0'"
          cd -

          pip uninstall conda-forge-feedstock-ops --yes
          rm -rf dist/*
          python -m build --sdist . --outdir dist
          pip install --no-deps --no-build-isolation dist/*.tar.gz
          cd ..
          python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ != '0.0.0'"
          cd -
          pip uninstall conda-forge-feedstock-ops --yes

          python -m pip install -v --no-deps --no-build-isolation -e .

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v4

      - name: build docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: false
          load: true
          tags: conda-forge-feedstock-ops:test

      - name: ensure cli runs
        run: |
          conda-forge-feedstock-ops-container --help

      - name: run tests
        run: |
          export RUST_BACKTRACE=full
          pytest -vvs tests
