name: tests

on:
  push:
    branches:
      - main
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4

      - uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 # v1
        with:
          environment-file: environment.yml

      - name: configure conda and install code
        run: |
          pip install --no-deps --no-build-isolation -e .

      - name: test versions
        run: |
          cd ..
          python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ != '0.0.0'"
          cd -

          pip uninstall conda-forge-feedstock-ops --yes
          rm -rf dist/*
          python -m build --sdist . --outdir dist
          pip install --no-deps --no-build-isolation dist/*.tar.gz
          cd ..
          python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ != '0.0.0'"
          cd -
          pip uninstall conda-forge-feedstock-ops --yes

          python -m pip install -v --no-deps --no-build-isolation -e .

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6
        with:
          context: .
          push: false
          load: true
          tags: conda-forge-feedstock-ops:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: run tests
        run: |
          pytest -vvs tests

      - name: ensure cli runs
        run: |
          conda-forge-feedstock-ops-container --help
